### ISSUE TITLE
HuffPost not working

### ISSUE THREAD

**Issue by RealLankinen** [jameslawler/react-native-rss-parser#12]
Hi, I'm using this module in my React Native app and I notice that at least HuffPost RSS feed (https://www.huffpost.com/section/world-news/feed) is not working. This is the error it prints: 

[xmldom error]	element parse error: Error: invalid tagName:t.length;o++)r(t[o]);return
[09:20:53] @#[line:undefined,col:undefined]

**Comment by jameslawler** [comment]
Hi @RealLankinen 

I added the huffpost example rss feed into the sample folder and added a test for it and everything works as expected. Please check out the code and make sure it works for you too when running `npm test`.

Commit: https://github.com/jameslawler/react-native-rss-parser/commit/4452290718a663c81c518988c1d07783891189f4

**Comment by QuevedoIB** [comment]
Huffpost still doesn't work, not a big deal for me, just letting you know. 

endpoint: "https://www.huffpost.com/section/world-news"

```
axios
      .get(endpoint)
      .then(response => rssParser.parse(response.data))
      .then(rssParsed => {
        setData(rssParsed);
        console.log(rssParsed);
      })
      .catch(function(error) {
        console.log(error);
      });
```

Throws following error:

<img width="750" alt="Screenshot 2020-05-04 at 10 28 34" src="https://user-images.githubusercontent.com/45363951/80948289-114bbe00-8df2-11ea-8b40-72fe9f8557c0.png">
