### ISSUE TITLE
Using Async/Await instead of .then

### ISSUE THREAD

**Issue by MarkoPoulin** [jameslawler/react-native-rss-parser#13]

**Comment by MarkoPoulin** [comment]
Using:

async componentWillMount() {

    ...

    const response = await fetch(url);
    const responseText = response.text();
    const rss = rssParser.parse(responseText); //... Error
 
    ...

}
Instead of: 

componentWillMount() {

   ...

  fetch(url)
      .then((response) => response.text())
      .then((responseData) => rssParser.parse(responseData))
      .then((rss) => {

        ...

     }
}
Any reason or idea this doesn't work.

**Comment by jameslawler** [comment]
Sorry for the really late reply, but the call to `rssParser.parse(responseData)` also returns a promise, so you would need to add an `await` here too.
